### PR TITLE
Explicitly disable precompilation

### PR DESCRIPTION
**Pull request by sbromberger**
Add explicit `__precompile__(false)` per https://groups.google.com/d/msg/julia-users/RLlYPlsT-dU/mhdukrp-AgAJ to disable precompilation.

### CODE REVIEW

**Comment by tkelman** [comment]
Yeah, I can reproduce the test failure when precompiled. Not sure if it'll be possible to fix, there are a lot of pointers in this package.
```
julia> Base.compilecache("LightXML")
"/home/tkelman/.julia/lib/v0.4/LightXML.ji"

julia> Pkg.test("LightXML")
INFO: Computing test dependencies for LightXML...
INFO: No packages to install, update or remove
INFO: Testing LightXML
running parse.jl ...
ERROR: LoadError: LoadError: UndefRefError: access to undefined reference
 in parse_string at /home/tkelman/.julia/v0.4/LightXML/src/document.jl:94
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:263
 in anonymous at no file:6
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:263
 in process_options at ./client.jl:308
 in _start at ./client.jl:411
while loading /home/tkelman/.julia/v0.4/LightXML/test/parse.jl, in expression starting on line 24
while loading /home/tkelman/.julia/v0.4/LightXML/test/runtests.jl, in expression starting on line 3
========================================[ ERROR: LightXML ]=========================================

failed process: Process(`/home/tkelman/Julia/julia/usr/bin/julia --check-bounds=yes --code-coverage=none --color=yes /home/tkelman/.julia/v0.4/LightXML/test/runtests.jl`, ProcessExited(1)) [1]

====================================================================================================
INFO: No packages to install, update or remove
ERROR: LightXML had test errors
 in error at ./error.jl:21
 in test at pkg/entry.jl:746
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71
```

**Comment by sbromberger** [comment]
Yeah, no worries. I'm not sure I like this idea that precompile follows all dependencies. Too easy to have something break the chain.

**Comment by tkelman** [comment]
That's why it's still an opt-in feature. The risks and failure cases aren't entirely understood yet across the community, will need a learning and experimentation period (aka now).

**Comment by sbromberger** [comment]
Well, it's opt-in except when it isn't. That is, I opted in LightGraphs, but I didn't opt-in LightXML. I have to explicitly opt-OUT all dependencies that don't play well with precompilation if I want it in my own package. That seems... backwards.

**Comment by sbromberger** [comment]
I don't know why travis is taking so long here.

**Comment by tkelman** [comment]
The JuliaLang org is pretty busy right now, lots of queued builds.

The fact that the opt-in automatically opts in any of your dependencies which haven't themselves explicitly opted out is interesting and does make it even more risky.

**Comment by stevengj** [comment]
I pushed my own commit since this commit hadn't been squashed.  (@sromberger, you should do `git commit --amend` followed by a forced push so that the PR does not contain incorrect commits.)

**Comment by tkelman** [comment]
I don't think it's too likely that we'll need to do a bisect on package code that's had fewer than 100 commits in total, but whatever.

**Comment by stevengj** [comment]
Note that #32 fixes the underlying problem and re-enables precompilation.

**Pull request closed without merging**
